[theme]
base = "light"
primaryColor = "#17150F"
backgroundColor = "#F2EFE8"
secondaryBackgroundColor = "#EBE6DB"
textColor = "#17150F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
